# Generated by Django 6.0.3 on 2026-05-16 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesPaciente',
            fields=[
                ('paciente', models.OneToOneField(limit_choices_to={'rol': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('esta_calibrado', models.BooleanField(default=False)),
                ('sensibilidad', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(3.0)])),
            ],
            options={
                'db_table': 'ajustes_paciente',
            },
        ),
    ]
