# Generated by Django 6.0.3 on 2026-03-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juego', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesPaciente',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.paciente')),
                ('esta_calibrado', models.BooleanField(default=False)),
                ('gesto_clic', models.CharField(max_length=50)),
                ('gesto_doble_clic', models.CharField(max_length=50)),
                ('sensibilidad', models.FloatField(default=1.0)),
            ],
            options={
                'db_table': 'ajustes_paciente',
            },
        ),
        migrations.CreateModel(
            name='SesionGaze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('tipo_evento', models.CharField(choices=[('fijacion', 'Fijación'), ('saccada', 'Sácada'), ('parpadeo', 'Parpadeo')], max_length=20)),
                ('duracion_ms', models.IntegerField(blank=True, null=True)),
                ('rehabilitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.rehabilitacion')),
            ],
            options={
                'db_table': 'sesion_gaze',
                'ordering': ['timestamp'],
            },
        ),
    ]
