# Generated by Django 6.0.3 on 2026-04-15 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajustespaciente',
            name='gesto_doble_clic',
        ),
        migrations.AlterField(
            model_name='ajustespaciente',
            name='gesto_clic',
            field=models.CharField(choices=[('fijacion', 'Fijacion'), ('parpadeo', 'Parpadeo')], default='fijacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='ajustespaciente',
            name='sensibilidad',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.DeleteModel(
            name='SesionGaze',
        ),
    ]
