# Generated by Django 6.0.3 on 2026-04-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_tracking', '0002_remove_ajustespaciente_gesto_doble_clic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajustespaciente',
            name='gesto_clic',
        ),
    ]
