# Generated by Django 6.0.3 on 2026-03-19 18:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minijuego',
            fields=[
                ('idMinijuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'minijuego',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('idNota', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=500)),
                ('fechaNota', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notas',
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('idProgreso', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'progreso',
            },
        ),
        migrations.CreateModel(
            name='Rehabilitacion',
            fields=[
                ('idRehabilitacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado')], default='pendiente')),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('puntuacionRehabilitacion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
            ],
            options={
                'db_table': 'rehabilitacion',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('idEdificio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('biblioteca', 'Biblioteca'), ('huerto', 'Huerto'), ('museo', 'Museo'), ('mercadillo', 'Mercadillo'), ('campanario', 'Campanario')], default='biblioteca')),
                ('estadoEdificio', models.CharField(choices=[('bloqueado', 'Bloqueado'), ('en_curso', 'En curso'), ('restaurado', 'Restaurado')], default='bloqueado')),
                ('puntuacionEdificio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('minijuego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='juego.minijuego')),
            ],
            options={
                'db_table': 'edificio',
            },
        ),
    ]
