# Generated by Django 6.0.3 on 2026-03-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juego', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='especialista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.especialista'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='notas',
            name='progreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.progreso'),
        ),
        migrations.AddField(
            model_name='rehabilitacion',
            name='progreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.progreso'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='rehabilitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.rehabilitacion'),
        ),
    ]
