# Generated by Django 6.0.3 on 2026-03-19 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juego', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='especialista',
            field=models.ForeignKey(limit_choices_to={'rol': 'especialista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progreso',
            name='paciente',
            field=models.OneToOneField(limit_choices_to={'rol': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notas',
            name='progreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.progreso'),
        ),
        migrations.AddField(
            model_name='rehabilitacion',
            name='progreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.progreso'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='rehabilitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.rehabilitacion'),
        ),
    ]
