# Generated by Django 6.0.3 on 2026-03-20 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='clinica',
        ),
        migrations.AddField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.clinica'),
        ),
    ]
